// PACK.SH : Thu 02 Dec 2021 10:59:49 PM EST
////////////////////////////////////////////////////////////////////////////////
// const.js: Constant values.

// const WIDTH = Math.floor(window.innerWidth*7/8);
const WIDTH = window.innerWidth;
const HEIGHT = window.innerHeight;

const LOG_LEVELS = {TRACE:5, DEBUG:4, INFO:3, WARN:2, ERROR:1, FATAL:0};
const LOG_LEVEL = LOG_LEVELS.TRACE;

const PI = 3.1415926;

const KEY_INIT = {down:false, time_down:0, time_up:0};

const KEYS_INIT = {
    "ArrowDown": KEY_INIT,
    "ArrowUp": KEY_INIT,
    "ArrowLeft": KEY_INIT,
    "ArrowRight": KEY_INIT,
    "Enter": KEY_INIT,
    "Space": KEY_INIT,
    "ControlLeft": KEY_INIT,
    "ControlRight": KEY_INIT,
    "ShiftLeft": KEY_INIT,
    "ShiftRight": KEY_INIT,
    "KeyA": KEY_INIT,
    "KeyS": KEY_INIT,
    "KeyD": KEY_INIT,
    "KeyW": KEY_INIT,
    "KeyQ": KEY_INIT,
    "KeyE": KEY_INIT,
    "KeyR": KEY_INIT,
    "KeyN": KEY_INIT,
    "Escape": KEY_INIT,
};

const BLOCK_TYPES = {DIRT: 0, GRASS: 1, WATER: 2, ROCK: 3};
const BLOCK_COLORS = {0: 0x5e480c, 1: 0x23800e, 2: 0x1e56bd, 3: 0x301222};

const ACTIONS = {TURN_CW:0, TURN_CCW:1, FORWARD:2, BACKWARD:3, LEFT:4, RIGHT:5, EAT:6};
const NUM_ACTIONS = Object.keys(ACTIONS).length;

const LEVELS = {
basic: {
    // TODO!
},
debug: {
    width: 300,
    height: 200,
    backgroundblock: BLOCK_TYPES.DIRT,
    blockarray: "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggrrrggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggrrrggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddgggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggrrrggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddrrddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggddddddddddddddddddddddddddddddddddddddddrrrrddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddggdddddddddddddddddddddddddddddddddddddddddgggggddddddddddddgggdddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddggddddddddddddddgggdddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggdddddddddddddddrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggddddddddddddddrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggddddddddddddddrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrdddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggdddddddddddddrrrrrrrrrrrrdddddddddddddddddddddddddddrrrddddddddddddddddddddddddddddddddddddddddddrrrdddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggrrrrrggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggddddddddddddrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrddddddddddddddddddddddddddddddddddddddddddrrddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggdddddddddddddrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggddddddddddddrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggddddddddddddgggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggddddddddddddrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddddddddddddggggddddddddddddggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggddddddddddddrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddddddddddddggggddddddddddddgggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrgggggggggggggggggrrrrggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggdddddddddddrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggrrrrggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggdddddddddddrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggrrrrggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggdddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggdddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrdddddggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggrrggggggggggggggggggggggggwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggggddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrgggggggggggggggrrrrgggggggggggggggggggggggwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggggggdddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrrrrrdddddddddddddddddddddddddgggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrgggggggggggggggrrrrgggggggggggggggggggggggwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggggggdddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrrrrrrrddddddddddddddddddddddddggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrgggggggggggggggggrrggggggggggggggggggggggggwwwwwwwwwwwggggggggggggggggggggggggggggggggggggggggddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrrrrrrrrrdddddddddddddddddddddddggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwgggggggggggggggggggggggggggggggggggggggggdddddddddddddrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrrrrrrrrrrdddddddddddddddddddddddgggddddddddddddddddddddddddggggdddddddddddddddddddddddddddddddddggggggggggggggggggggggggrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggggggggggwwwwwwwggggggggggggggggggggggggggggggggggggggggggddddddddddddddrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddggggggggdddddddddddddddddddddddddddddddgggggggggggggggggggggggggrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggggggwwwwwwggggggggggggggggggggggggggggggggggggggggggdddddddddddddddrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddggggggggggddddddddddddddddddddddddddddddgggggggggggggggggggggggggggrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggggggggggggwwwwwggggggggggggggggggggggggggggggggggggggggggdddddddddddddddrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrdddddddddggdddddddddddddddddddddddddddddddddddggggggggggggdddddddddddddddddddddddddddddggggggggggggggggggggggggggggrrrrrrrrrggggggggggggggggggggggggggggggggggggggggggggggggwwwggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrdddddddddggggddddddddddddddddddddddddddddddddggggggggggggggddddddddddddddddggggdddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwgggggggggggggggggggggggggggggggggggggdgggddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrddddddddddggggdddddddddddddddddddddddddddddggggggggggggggggggdddddddddddddddggggddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrdddddddddddggddddddddddddddddddddddddddddggggggggggggggggggggdddddddddddddddggggddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwgggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrdddddddddddddddddrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggdddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrdddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggdddddddddddddddddddddddddddrrddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggddddddddddddddddddddddddddrrrrddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrdddddddrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggdddddddddddddddddddddddddddrrrrdddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwgggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwggggggggggggggggggggggggggggdddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwgggggggggggggggggggggggggggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwgggggggggggggggggggggggggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwgggggggggggggggggggggggddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwgggggggggggggggggggggggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwggggggggggggggggggggggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwggggggggggggggggggggggddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwggggggggggggggggggggggggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwggggggggggggggggggggggggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwgggggggggggggggggggggggggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwgggggggggggggggggggggggggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddgggggggggggggggddddddddddddddddddddddddddddddggggdddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggwwwwwwwwwwggggggggggggggdgggggggggddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrggggggggggrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddggggggggggggdddddddddddddddddddddddddddddddggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggwwwwwwwwwggggggggggggggdddgggggggdddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddgggggggggddddddddddddddddddddddddddddddddggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggwwwwwwwwwwgggggggggggggddddddgggdddddddddddddddggdddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggwwwwwwwwwwgggggggggggdddddddddddddddddddddddddggggddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggwwwwwwwwwwggggggggggddddddddddddddddddddddddddggggdddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggggrrrrrrrrrddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggwwwwwwwwwwgggggggddddddddddddddddddddddddddddddggddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggrrrrrrrrddddddddddddddgggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggwwwwwwwwwwgggggggddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggrrrrrrrdddddddddddddddgggdddddgggddddddddddddddddddddddddddddddddddddddddddddddgggggggggddddddddddddddddddgggdddddddddddddddddddddgggdddddddddddddddddddddggggggggggggggwwwwwwwwwwwgggggggddddddddddddddddddddddddrrddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggggrrrrrddddddddddddddddddddddddgggddddddddddrrrrddrrddddddddddddgggddddggdddddddgggggggggddddddddddddddddddgggdddddddddddddddddddddgggddddddddddddddddddddgggggggggggggggwwwwwwwwwwggggggggddddddddddddddddddddddddrrrdddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggrrrrdddddddddddddddddddddddddgggddddddddddrrrrrrrrrddddddddddgggggggggggddddddggggggggdddddddddddddddddddgggdddddddddddddddddddddgggddddddddddddddddddddgggggggggggggggwwwwwwwwwwggggggggddddddddddddddddddddddddrrrdddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggrrdddddddddddddddddddddddddddddddddddddddrrrrrrrrrrdddddddddgggggggggggddddddggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggwwwwwwwwwwwggggggggddddddddddddddddddddddddrrddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrdddddddddgggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggwwwwwwwwwwwggggggggddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggwwwwwwwwwwwgggggggggdddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggwwwwwwwwwwwgggggggggdddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggwwwwwwwwwwwggggggggggdddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggwwwwwwwwwwwgggggggggggddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggggggggggggddrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggwwwwwwwwwwggggggggggggdddddddddggddddddgggdddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrggggggggggggggggggggggggggggggggggggggggggggggggggggggdrrrrddddddddddddddddddddddddrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggwwwwwwwwwwggggggggggggddddddddgggddddddgggddddddddddddddddddddddddddddrrrrrrrrrrrgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdrrrrdddddddddddddddddddddddrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggwwwwwwwwwwgggggggggggggddddddddgggddddddgggddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdrrddddddddddddddddddddddddrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrddddddddddddddddddddddddddddddddggggggggggggggggggggwwwwwwwwwwwgggggggggggggdddddddddggdddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrddddddddddddddddddddddddddddggggggggggggggggggggggwwwwwwwwwwggggggggggggggddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrddddddddddddddddddddddddddggggggggggggggggggggggwwwwwwwwwwwggggggggggggggdddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddrrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrddddddddddddddddddddddddggggggggggggggggggggggwwwwwwwwwwwgggggggggggggggddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddrrrrdddddddddrrrdddddddddddddddddddddddddgggggddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrddddddddddddddddddddddgggggggggggggggrrrggggwwwwwwwwwwwggggggggggggggggddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddrrrrdddddddddddddddddddddddddddddddddgggggggggggdddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrddddddddddddddddddddggggggggggggggggrrrggggwwwwwwwwwwwggggggggggggggggdddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddrrrrddddddddddddddddddddddddddddgggggggggggggggggdddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrdddddddddddddddddddgggggggggggggggggrrrggggwwwwwwwwwwgggggggggggggggggddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddrrrrdddddddddddddddddggggggggggggggggggggdddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrddddddddddddddddddgggggggggggggggggrrrgggwwwwwwwwwwwgggggggggggggggggdddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddrrrrddddddddddddddddgggggggggggggggggggggdddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrddddddddddddddddggggggggggggggggggggggggwwwwwwwwwwggggggggggggggggggdddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddrrrrddddddddddddddgggggggggggggggggggggggggddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddgggggggggggggggggggggggwwwwwwwwwwwggggggggggggggggggddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddggggggggggggrrrggggggggwwwwwwwwwwwggggggggggggggggggdddddddddddddgggddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddrrrdddddddddddgggggggggggggggggggggggggggggdddddddddrrrddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddggggggggggggrrrgggggggwwwwwwwwwwwgggggggggggggggggggdgggdddddddddgggdddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddrrrrdddddddddggggggggggggggggggggggggggggggdddddddrrrrrrrrdddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddggggggggggggrrrgggggggwwwwwwwwwwwgggggggggggggggggggggggdddddddddgggdddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddrrrrddddddddggggggggggggggggggggggggggggggggdddddrrrrrrrrrrdddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddgggggggrrrrgggggggggggwwwwwwwwwwwgggggggggggggggggggggggdddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddrrrddddddddgggggggggggggggggggggggggggggggggddddrrrrrrrrrrrrddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddgggggggrrrrggggggrrggwwwwwwwwwwwwgggggggggggggggggggdggdddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggdddrrrrrrrrrrrrrrddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddgggggggrrggggggrrrrgwwwwwwwwwwwwgggggggggggggggggggddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggdddrrrrrrrrrrrrrrrddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddggggggggggggggrrrrwwwwwwwwwwwwwgggggggggggggggggggddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddgrrrrggggggggggrrgwwwwwwwwwwwwggggggggggggggggggggddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggdrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddrrrrggrrrggggggggwwwwwwwwwwwwggggggggggggggggggggddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddgrrgggrrrgggggggwwwwwwwwwwwwwggggggggggggggggggggddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddgggggrrrgggggggwwwwwwwwwwwwgggggggggggggggggggggdddddddddddddddrrrrdddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddgggggggggggggggwwwwwwwwwwwwgggggggggggggggggggggdddddddddddddddrrrrdddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddggggggggggggggwwwwwwwwwwwwgggggggggggggggggggggdddddddrrrdddddrrrrdddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddggggggggggggggwwwwwwwwwwwwgggggggggggggggggggggdddddddrrrddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddggggggggggggwwwwwwwwwwwwwgggggggggggggggggggggdddddddrrrddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddggggggggggwwwwwwwwwwwwwwgggggggggggggggggggggdddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddggggggggwwwwwwwwwwwwwwggggggggggggggggggggggdddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddggggggwwwwwwwwwwwwwwgggggggggggggggggggggggdddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrgggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddggdwwwwwwwwwwwwwwwgggggggggggggggggggggggdddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrgggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddwwwwwwwwwwwwwwwggggggggggggggggggggggggdddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddwwwwwwwwwwwwwwgggggggggggggggggggggggggddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddwwwwwwwwwwwwwwggggggggggggggggggggggggggdddddddddddddggdddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddwwwwwwwwwwwwwwwggggggggggggggggggggggggggddddddddddddgggddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddwwwwwwwwwwwwwwwgggggggggggggggggggggggggggddddddddddddgggddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggddddggdddddddggddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddrrrrrrrrrrrrdddrrrrrrrrrrrrrrdddddddddddwwwwwwwwwwwwwwwggggggggggggggggggggggggggggdddggggdddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddrrrrrrrrdddddrrrrrrrrrrrrrrddddddddddwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggdddggggdddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddrrrrrrrrrrrrrdddddddddwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggddddggdddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddrrrrrrrrrrrrrddddddddwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddrrrrrrrrrrrddddddddwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddrrrrrrrrrrrddddddddwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddrrrrrrrrrddddddddwwwwwwwwwwwwwwwwdgggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddrrrrrrrddddddddwwwwwwwwwwwwwwwwdggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggddddddddggggggggggggggggggggggggggggggggggggggggggggggggrrrgggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddggddddddddddddddddrrrdddddddddwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggddddddddddgggggggggggggggggggggggggggggggggggggggggggggggrrrgggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddggggddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwdgggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggdddddddddddgggggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddggggdddddddddddddddddddddddddwwwwwwwwwwwwwwwwwdggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggdddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddggggddddddddddddddddddddddddwwwwwwwwwwwwwwwwwdgggggggggggggggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggdddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwddgggggggggggggggggggggggggggggggggggddddddddddddddgggdddddddddddddddddddddddgggggggggggggggggggggggggggggggggggdddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwdggggggggggggggggggggggggggggggggggggdddggdddddddddggggdddddddddddddddddddddddgggggggggggggggggggggggggggggggggdddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwdgggggggggggggggggggggggggggggggggggggdddgggddddddddggggdddddddddddddddddddddddddggggggggggggggggggggggggggggggdddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwdggggggggggggggggggggggggggggggggggggggdddgggddddddddggggdddddddddddddddddddddddddddggggggggggggggggggggggggggdddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwdgggggggggggggggggggggggggggggggggggggggdddggdddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggdddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwddgggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwdggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddggddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwdgggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddgggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddgggdddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddgggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddgggdddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddgggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddggddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggrrrggggggggggdddddddddddddddddddddggggggggddddddddddgggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggrrrggggggggggdddddddddddddddddddddddggggggddddddddddgggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddrrrrdddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggrrrggggggggggdddddddddddddddddddddddddddddddddddddddgggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggdddddddddddddddddddddddddddddddddddddddddddddrrrrdddddddddddddddddddddddddddddddddddddddddddrrrrdddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddrrrrddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwgggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggdddddddddddddddddddddggdddddddddddddddgggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggddddddddddddddddddddddddddddrrdddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwdgggggggggggggggggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggddddddddddddddddddddggggdddddddddddddddggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggdddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwdggggggggggggggggggggggggggggggggggggggggggggggggggwdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggdddddddddddddddddddgggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggdddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdgggggggggggggggggggggggggggggggggggggggggggggggggggwwwdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggddddddddddddddddddgggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddgggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddgggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddggggggggggggdddddddddddddddddddddddddgggggggdddddddddddddggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwddddddddddddddddddddddddddddddddddrrrdddddddddddddddddddddddgggdddddgggggggggddddddddddddddddddddddddddddgggggggdddddddddddddggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwddddddddddddgggdddddddddddddddddrrrddddddddddddddddddddddggggdddddgggddddddddddddddddddddddddddddddddddgggggggdddddddddddddggggdddddgggggddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwdddddddddddgggdddddddddddddddddrrrddddddddddddddddddddggggggddddddddddddddddddddddddddddddddddddddddddggggggdddddddddddddddddddddddgggggdddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwdddddddddgggdddddddddddddddddrrrddddddddddddddddddddggggggddddddddddddddddddddddddddddddddddddddddgggddddddddddddddddddddddddddddgggggdddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwddddddddgggddddddddddddddddddddddddddddddddddddddddgggggddddddddddddddddddddddddddddddddddddddddggggddddddddddddddddddddddddddddgggggdddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddddggggdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwdddddddddddddddddddddrrrrddddddddddddddddddddddddddddddddddddddrrrrddddddddddddddddddddddddddggddddddddgggdddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwddddddddddddddddddddrrrrddgggdddddddddddddddddddddddddddddddrrrrrrrrddddddddddddddddddddddddddddddddddgggdddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddrrdgggggddddddddddddddddddddddddddddddrrrrrrrrrrdddddddddddddddddddddddddddddddddggggdddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddgggggdddddddddddddddddddddddddddddrrrrrrrrrrrrddddddddddddddddddddddddddddddddggggdddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddgggggddddddddddddddddddddddddddddrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddgggddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddggggdddddddddddddddddddddddddddddrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggrrrrggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddrrrddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddrrrddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrgggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddggggddddddddddddddrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddrrrdddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddggggddddddddddddddrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddggggdddddddddddddrrrrrrrrrrrrrrrrrrrdddddddddddddddrrdddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrgggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddggggdddddddddddddrrrrrrrrrrrrrrrrrrrddddddddddddddrrrrddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrgggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrddddddddddddddrrrrddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrgggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrddddddddddddddddrrddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrrrgggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrrggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrrrgggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddddddddddddddrrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrrrrggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddggggddddddddddddddrrrrrrrrrrrrrdddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrrrgggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddggggdddddddddddddddrrrrrrrrrrrddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddggggddddddddddddddddrrrrrrrrrdddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddggggddddddddddddddddddrrrrrdddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggrrrggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddwwwwwddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
},
};
////////////////////////////////////////////////////////////////////////////////
// util.js: Utility functions.

function BlockCharToBlockType(c) {
    if (c == "r") {
        return BLOCK_TYPES.ROCK;
    } else if (c == "g") {
        return BLOCK_TYPES.GRASS;
    } else if (c == "w") {
        return BLOCK_TYPES.WATER;
    } else if (c == "d") {
        return BLOCK_TYPES.DIRT;
    } else {
        return -1;
    }
}

function ShuffleArray(array) {
    let currentIndex = array.length,  randomIndex;

    while (currentIndex != 0) {
        randomIndex = Math.floor(Math.random() * currentIndex);
        currentIndex--;

        [array[currentIndex], array[randomIndex]] = [array[randomIndex], array[currentIndex]];
    }

    return array;
}

function Linspace(a,b,d,incl=true) {
    let t = [];
    const end = incl ? b : b-d;
    for (let i = a; i <= end; i += d) {
        t.push(i);
    }
    return t;
}

function Max(ar) {
    return Math.max.apply(Math, ar);
}

function Min(ar) {
    return Math.min.apply(Math, ar);
}

function Sigs(n, dig=3) {
    return Math.round(n * Math.pow(10, dig)) / Math.pow(10, dig);
}

function RandInt(l,h) {
    // Range = [l,h-1]
    return Math.floor(Math.random() * (h-l)) + l;
}

function RandID(len=6) {
    let result           = "";
    let characters       = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let charactersLength = characters.length;
    for (let i = 0; i < len; i++ ) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
}

function RandNormal(mu, sigma, nsamples=6){
    if(!sigma) sigma = 1
    if(!mu) mu=0

    var run_total = 0
    for(var i=0 ; i<nsamples ; i++){
       run_total += Math.random()
    }

    return sigma*(run_total - nsamples/2)/(nsamples/2) + mu
}

function Cot(v) { return 1 / Math.tan(v); }
function Sin(v) { return Math.sin(v); }
function Cos(v) { return Math.cos(v); }
function Csc(v) { return 1 / Math.sin(v); }
function Ln(v) { return Math.log(v) / Math.log(Math.E); }
function Sqr(v) { return Math.pow(v,2); }
function Sqrt(v) { return Math.sqrt(v); }
function Cube(v) { return Math.pow(v,3); }
function Fourth(v) { return Math.pow(v,4); }
function Exp(v) { return Math.exp(v); }
function Log10(v) { return Math.log10(v); }
function Pow(b,e) { return Math.pow(b, e); }
function Abs(v) { return Math.abs(v); }
function Round(v) { return Math.round(v); }

// Returns value "v" limited by "min" and "max".
function Clamp(v, min, max) {
    if (v < min) { return min; }
    if (v > max) { return max; }
    return v;
}

function FuzzyEquals(v1, v2, fuzz) {
    return Abs(v1 - v2) < fuzz;
}

function Contains(x, y, rx, ry, rw, rh) {
    return x > rx - rw/2 && x < rx + rw/2 && y > ry - rh/2 && y < ry + rh/2;
}

function Log(msg) { LogDebug(msg); }

function LogFatal(msg) {
    if (LOG_LEVEL >= LOG_LEVELS.FATAL) { console.log("FATL: "+msg); }
}

function LogError(msg) {
    if (LOG_LEVEL >= LOG_LEVELS.ERROR) { console.log("ERR : "+msg); }
}

function LogWarn(msg) {
    if (LOG_LEVEL >= LOG_LEVELS.WARN) { console.log("WARN: "+msg); }
}

function LogInfo(msg) {
    if (LOG_LEVEL >= LOG_LEVELS.INFO) { console.log("INFO: "+msg); }
}

function LogDebug(msg) {
    if (LOG_LEVEL >= LOG_LEVELS.DEBUG) { console.log("DBUG: "+msg); }
}

function LogTrace(msg) {
    if (LOG_LEVEL >= LOG_LEVELS.TRACE) { console.log("TRAC: "+msg); }
}
////////////////////////////////////////////////////////////////////////////////
// main.js: Main program.

const canvas = document.getElementById("canvas");
const app = new PIXI.Application({
    width: WIDTH, height: HEIGHT,
    backgroundColor: 0x000000,
    resolution: window.devicePixelRatio || 1,
    view: canvas,
});

PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;

const G_content = new pixi_viewport.Viewport({
    screenWidth: WIDTH,
    screenHeight: HEIGHT,
    worldWidth: WIDTH,
    worldHeight: HEIGHT,
    interaction: app.renderer.plugins.interaction,
});

G_content.drag().pinch().wheel().decelerate();

let G_draw_layers = [];
G_draw_layers.push(new PIXI.Container()); // 0: Background.
G_draw_layers.push(new PIXI.Container()); // 1: Mid-Background.
G_draw_layers.push(new PIXI.Container()); // 2: Main stage layer.
G_draw_layers.push(new PIXI.Container()); // 3: Foreground.
G_draw_layers.push(new PIXI.Container()); // 4: UI.
let G_graphics = [];
G_graphics.push(new PIXI.Graphics()); // 0: Background Graphics.
G_graphics.push(new PIXI.Graphics()); // 1: Mid-Background Graphics.
G_graphics.push(new PIXI.Graphics()); // 2: Main stage Graphics.
G_graphics.push(new PIXI.Graphics()); // 3: Foreground Graphics.
G_graphics.push(new PIXI.Graphics()); // 4: UI Graphics.
app.stage.addChild(G_content);
G_content.addChild(G_draw_layers[0]);
G_draw_layers[0].addChild(G_graphics[0]);
G_content.addChild(G_draw_layers[1]);
G_draw_layers[1].addChild(G_graphics[1]);
G_content.addChild(G_draw_layers[2]);
G_draw_layers[2].addChild(G_graphics[2]);
G_content.addChild(G_draw_layers[3]);
G_draw_layers[3].addChild(G_graphics[3]);
G_content.addChild(G_draw_layers[4]);
G_draw_layers[4].addChild(G_graphics[4]);

let G_stage = null;

let G_keys = KEYS_INIT;

let G_pause = false;
let G_needs_update = false;
let G_loaded = false;
let G_actions = [];

function Init() {
    G_stage = new MainMenu();
    G_needs_update = true;
}

app.ticker.add((dT) => {
    if (G_pause == true) { return; }
    if (G_loaded == false) { Init(); G_loaded = true; }
    if (G_stage == null) { return; }
    
    G_stage.Update(dT);
    
    // TODO: Track lurkers and lerpers for destroy-ing.

    // If some class set the global update value to true, redraw graphics.
    if (G_needs_update == true) {
        for (let i = 0; i < G_graphics.length; i++) {
            G_graphics[i].clear();
        }
        G_stage.Draw();
        G_needs_update = false;
    }

    while (G_actions.length > 0) {
        let act = G_actions[0];

        LogInfo("Global action " + act + ".");

        if (act.includes("load debug")) {
            // Action: load TestGame.

            G_stage.Destroy();
            delete G_stage;
            G_stage = new GameStage("debug");
            G_needs_update = true;

        }

        G_actions.splice(0, 1);
    }

});
////////////////////////////////////////////////////////////////////////////////
// entities.js: Entities.

class Entity {
    constructor(a) {
        this.active = true;

        this.id = a.id;
        this.x = a.x;
        this.y = a.y;

        this.sprites = {};
        this.texts = {};
        this.textures = {};
    }

    AddSprite(a) {
        let id = a.id;
        let x = a.x;
        let y = a.y;
        let w = a.width;
        let h = a.height;
        let fname = "gfx/"+a.filename;
        let anc = {x:0.5, y:0.5};
        let dl = 2;

        if (a.hasOwnProperty("anchor_x")) { anc.x = a.anchor_x; }
        if (a.hasOwnProperty("anchor_y")) { anc.y = a.anchor_y; }
        if (a.hasOwnProperty("draw_layer")) { dl = a.draw_layer; }
        
        this.textures[id] = PIXI.Texture.from(fname);

        this.sprites[id] = new PIXI.Sprite(this.textures[id]);
        this.sprites[id].anchor.set(anc.x, anc.y);
        this.sprites[id].position.set(x, y);
        this.sprites[id].width = w;
        this.sprites[id].height = h;
        this.sprites[id].draw_layer = dl;
        G_draw_layers[dl].addChild(this.sprites[id]);
    }

    AddText(a) {
        let id = a.id;
        let x = a.x;
        let y = a.y;
        let t = a.text;
        let ff = "Courier New";
        let fs = 12;
        let fc = 0xffffff;
        let align = "center";
        let dl = 4;

        if (a.hasOwnProperty("fontFamily")) { ff = a.fontFamily; }
        if (a.hasOwnProperty("fontSize")) { fs = a.fontSize;}
        if (a.hasOwnProperty("fill")) { fc = a.fill; }
        if (a.hasOwnProperty("align")) { align = a.align; }
        if (a.hasOwnProperty("draw_layer")) { dl = a.draw_layer; }

        let anc = {x:0.5, y:0.5};
        if (align == "left") { anc.x = 0; }
        else if (align == "right") { anc.x = 1; }

        this.texts[id] = new PIXI.Text(t, {
            fontFamily: ff, fontSize: fs, fill: fc, align: align,
        });
        this.texts[id].anchor.set(anc.x, anc.y);
        this.texts[id].position.set(x, y);
        this.texts[id].draw_layer = dl;
        G_draw_layers[dl].addChild(this.texts[id]);
    }

    Loaded() {
        let loaded = true;
        for (let k in this.textures) {
            if (k.loaded == false) {
                loaded = false;
                break;
            }
        }
        return loaded;
    }

    Destroy() {
        this.active = false;
        for (let k in this.sprites) {
            G_draw_layers[this.sprites[k].draw_layer].removeChild(this.sprites[k]);
            delete this.sprites[k];
        }
        for (let k in this.texts) {
            G_draw_layers[this.texts[k].draw_layer].removeChild(this.texts[k]);
            delete this.texts[k];
        }
        for (let k in this.textures) {
            this.textures[k].destroy();
            delete this.textures[k];
        }
    }

    Update(dT) {}
    Draw() {}
}

// Lerper is a cool class. It will call a callback and provide a value between
// 0 and 1 until the entire Lerp duration has completed. The callback can also
// optionally have a second parameter that is given as "true" on final call.
// Lerpers can also be drawn for debug purposes with the "d" function.
// Lerper is a "quasi-entity".
class Lerper {
    constructor(dur, cb, d=function(){}) {
        this.dur = dur;
        this.cb = cb;
        this.d = d;
        this.elapsed = 0;
        this.active = true;
        this.vals = {good:false}; // Can hold additional values per lerper.
    }

    Destroy() {}

    Update(dT) {
        // On the final tick, call the callback with an argument of 1 = 100%.
        if (this.elapsed + dT > this.dur) {
            this.cb(1, true);
            this.active = false;
            return;
        }

        // Otherwise, do the normal routine.
        this.elapsed += dT;

        this.cb(this.elapsed / this.dur, false);
    }

    Draw() {
        this.d();
    }
}

// Lurker is similar to lerper, but it will run continuously until the callback
// returns a value of "false". At that point it no longer calls the callback.
// Lurkers can also be drawn for debug with the "d" function.
// Lerper is a "quasi-entity".
class Lurker {
    constructor(cb, d=function(){}) {
        this.cb = cb;
        this.d = d;
        this.elapsed = 0;
        this.active = true;
        this.vals = {good:false}; // Can hold additional values per lurker.
    }

    Destroy() {}

    Update(dT) {
        if (!this.active) { return; }

        this.elapsed += dT;

        this.active = this.cb(dT);
    }

    Draw() {
        this.d();
    }
}

class Creature extends Entity {
    constructor(x,y) {
        super({id:"creature",x:x,y:y});

        this.color = RandInt(0, 0xffffff);

        this.action = -1;
        this.facing = 0; // 0:N, 1:E, 2:S, 3:W.
    }

    TurnCW() {
        this.facing = (this.facing + 1) % 4;
    }
    TurnCCW() {
        this.facing = (this.facing - 1) % 4;
    }

    GetForwardDisplacement() {
        if (this.facing == 0) {
            return [0,-1];
        } else if (this.facing == 1) {
            return [1,0];
        } else if (this.facing == 2) {
            return [0,1];
        } else if (this.facing == 3) {
            return [-1,0];
        } else {
            return [0,0];
        }
    }

    Process() {
        this.action = RandInt(0, NUM_ACTIONS);
    }
    
    Draw() {
        G_graphics[0].lineStyle(0);
        G_graphics[0].beginFill(this.color);
        G_graphics[0].drawRect(this.x, this.y, 1, 1);
        G_graphics[0].endFill();
    }
}
////////////////////////////////////////////////////////////////////////////////
// stages.js: Game stages. 

class Stage extends Entity {
    constructor() {
        super({"id":"stage", "x":0, "y":0});
        this.active = true;
    }

    KeyDown(k){}
    KeyUp(k){}

    Reset() {}
}

class MainMenu extends Stage {
    constructor() {
        super();

        this.menu_line_x = 200;
        this.menu_line_x_spacing = 10;
        this.menu_line_y = 100;
        this.menu_line_y_spacing = 100;
        this.menu_fontSize = 64;
        this.menu_num_items = 2;

        // Play menu item.
        this.AddText({id:"play", x: this.menu_line_x + this.menu_line_x_spacing,
            y: this.menu_line_y, text:"Play", fontSize: this.menu_fontSize,
            align:"left"});

        // About menu item.
        this.AddText({id:"about", x: this.menu_line_x + this.menu_line_x_spacing,
            y: this.menu_line_y + this.menu_line_y_spacing, text:"About",
            fontSize: this.menu_fontSize, align:"left"});

        // Menu pointer.
        this.AddText({id:"ptr", x: this.menu_line_x - this.menu_line_x_spacing,
            y: this.menu_line_y, text:">", fontSize: this.menu_fontSize,
            align:"right"});

        this.pointer = this.texts["ptr"];

        this.pointer_moved = false;
    }

    Update(dT) {
        if (this.active == false) { return; }

        if (G_keys.KeyQ.down) {
            // DEBUG KEY.

            G_actions.push("load debug");
            this.active = false;

        } else if (G_keys.KeyW.down || G_keys.ArrowUp.down) {

            if (this.pointer_moved == false &&
                    this.pointer.y > this.menu_line_y+1) {
                this.pointer_moved = true;
                this.pointer.y -= this.menu_line_y_spacing;
            }

        } else if (G_keys.KeyS.down || G_keys.ArrowDown.down) {

            if (this.pointer_moved == false &&
                    this.pointer.y < this.menu_line_y + 
                    (this.menu_line_y_spacing*(this.menu_num_items-1))) {
                this.pointer_moved = true;
                this.pointer.y += this.menu_line_y_spacing;
            }
        
        } else if (G_keys.Enter.down) {

            let item_number = Round((this.pointer.y - this.menu_line_y) / this.menu_line_y_spacing);
            if (item_number == 0) {
                this.active = false;
                G_actions.push("load debug");
            } else if (item_number == 1) {
                // TODO: other buttons.
            }

        } else {

            this.pointer_moved = false;

        }
    }
}

class GameStage extends Stage {
    constructor(lvlname) {
        super();

        this.level_name = lvlname;
        this.level = JSON.parse(JSON.stringify(LEVELS[lvlname]));

        this.width = this.level.width;
        this.height = this.level.height;

        this.blocks = [];
        for (let r = 0; r < this.height; r++) {
            this.blocks.push([]);
            for (let c = 0; c < this.width; c++) {
                let pixnum = r*300+c;
                this.blocks[r][c] = BlockCharToBlockType(this.level.blockarray[pixnum]);
            }
        }

        // this.AddSprite({id:"bg", x:WIDTH/2, y:HEIGHT/2, 
        //     width:GAME_WIDTH, height:GAME_HEIGHT,
        //     draw_layer:0, filename:"background.png"});

        this.creatures = {};
    }

    KeyDown(k) {
        if (k == "KeyN") {
            // Every creature takes a single step.
            let keys = [];
            for (let c in this.creatures) {
                let bt = this.blocks[c.y][c.x];
                if (bt == BLOCK_TYPES.WATER || bt == BLOCK_TYPES.ROCK) {
                    delete this.creatures[c];
                    continue;
                }
                this.creatures[c].Process();
                keys.push(c);
            }
            ShuffleArray(keys);
            for (let i = 0; i < keys.length; i++) {
                let c = this.creatures[keys[i]];

                // Handle Actions.
                if (c.action == ACTIONS.TURN_CW) {
                    c.TurnCW();
                } else if (c.action == ACTIONS.TURN_CCW) {
                    c.TurnCCW();
                } else if (c.action == ACTIONS.FORWARD) {
                    let dis = c.GetForwardDisplacement();
                    let btf = this.blocks[c.x+dis[0]][c.y+dis[1]];
                    if (btf == BLOCK_TYPES.DIRT || btf == BLOCK_TYPES.GRASS) {
                        c.x += dis[0];
                        c.y += dis[1];
                    }
                } else if (c.action == ACTIONS.BACKWARD) {
                }
            }
            G_needs_update = true;
        } else if (k == "KeyC") {
            this.creatures[RandID()] = new Creature(RandInt(0, this.width), RandInt(0, this.height));
            G_needs_update = true;
        }
    }

    Reset() {}

    Update(dT) {
        if (this.active == false) { return; }
    }

    Draw() {
        // DEBUG: background.
        G_graphics[0].lineStyle(0);
        G_graphics[0].beginFill(0x006600);
        G_graphics[0].drawRect(0, 0, this.width, this.height);
        G_graphics[0].endFill();

        G_graphics[0].lineStyle(0);
        for (let r = 0; r < this.height; r++) {
            for (let c = 0; c < this.width; c++) {
                G_graphics[0].beginFill(BLOCK_COLORS[this.blocks[r][c]]);
                G_graphics[0].drawRect(c, r, 1, 1);
                G_graphics[0].endFill();
            }
        }

        for (let c in this.creatures) {
            this.creatures[c].Draw();
        }

        // Draw Exits.
        // G_graphics[3].lineStyle(1, 0x00ff00);
        // for (let i=0; i < this.exits.length; i++) {
        //     let k = this.exits[i];
        //     G_graphics[3].beginFill(0x006600, 0.5);
        //     G_graphics[3].drawRect(
        //         GAME_LEFT + (k.x - k.width/2) * GAME_SCALE,
        //         GAME_TOP + (k.y - k.height/2) * GAME_SCALE,
        //         k.width * GAME_SCALE, k.height * GAME_SCALE);
        //     G_graphics[3].endFill();
        // }
    }
}
////////////////////////////////////////////////////////////////////////////////
// listeners.js: Interaction listeners.

document.addEventListener("keydown", function(evt) {
    if (G_keys.hasOwnProperty(evt.key) == false) {
        G_keys[evt.code] = {down: true, time_down: 0, time_up: 0};
    }

    G_keys[evt.code].down = true;
    G_keys[evt.code].time_down = Date.now();
    G_stage.KeyDown(evt.code);
}, false);

document.addEventListener("keyup", function(evt) {
    if (G_keys.hasOwnProperty(evt.key) == false) {
        G_keys[evt.code] = {down: false, time_down: 0, time_up: 0};
    }
    
    G_keys[evt.code].down = false;
    G_keys[evt.code].time_up = Date.now();
    G_stage.KeyUp(evt.code);
}, false);
////////////////////////////////////////////////////////////////////////////////
